repos:
-   repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear]
      args: ["--show-source"]
-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        description: Format files with clang-format
        entry: clang-format -i --verbose
        language: system
        files: ^.*\.(c|cc|cxx|cpp|cu|h|hpp|hxx|cuh|proto)$
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
