name: Python tests

on:
  push:
  schedule:
    - cron: "0 6,18 * * *"
  release:
    types: [released]

jobs:
  run_python_tests:
    name: Python Tests on ${{ matrix.os }} w/ Py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7"]
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Setup Python ${{ matrix.python-version }} env
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Ensure latest pip & wheel
        run: "python -m pip install --upgrade pip"
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.16.x'
      - name: Install PyTorch
        # Need to explicitly ask for non-CUDA version on Linux.
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
               pip install torch==1.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
               pip install numpy pytest-forked gym
             else
               pip install torch numpy pytest-forked gym
             fi
        shell: bash
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install moolib
        # pip installing makes site-packages not be part of sys.path,
        # so torch won't be found by our cmake check. TODO: Fix.
        # run: "USE_CUDA=0 pip install ."
        run: "USE_CUDA=0 python setup.py install"
      - name: Run tests
        run: "python -um pytest -svx --forked test/unit test/integration"
